server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/mydatabase
    username: myuser
    password: secret
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour
  google:
    places-key: ${GOOGLE_PLACES_KEY}
  scanner:
    default-confidence-threshold: ${SCANNER_DEFAULT_CONFIDENCE:0.4}
    default-max-results: ${SCANNER_DEFAULT_MAX_RESULTS:3}
ml:
  classifier-service:
    url: ${CLASSIFIER_API_URL:http://localhost:8003}
  caption-service:
    url: ${CAPTION_API_URL:http://localhost:8004}
