"""concept_registry_a.py — Phase 1 concepts: furniture, electronics, kitchenware, clothing, office."""

# fmt: (canonical_label, aliases, parent, tags, visual_description)

CONCEPTS_A = {
    "furniture": [
        ("chair","","furniture","seating","standard chair with backrest and legs"),
        ("sofa","couch|settee|lounge","furniture","seating|living_room","upholstered multi-seat sofa"),
        ("loveseat","two-seater sofa","sofa","seating|living_room","compact two-person upholstered sofa"),
        ("armchair","easy chair|lounge chair","chair","seating|living_room","single upholstered chair with armrests"),
        ("recliner","reclining chair|lounger","armchair","seating|living_room","padded chair with reclining backrest"),
        ("rocking chair","rocker","chair","seating|living_room","chair with curved wooden rocking base"),
        ("office chair","desk chair|ergonomic chair","chair","seating|office","rolling chair with adjustable height"),
        ("dining chair","kitchen chair","chair","seating|kitchen","upright chair for dining table"),
        ("bar stool","counter stool","chair","seating|kitchen","tall backless counter seating stool"),
        ("folding chair","collapsible chair","chair","seating|portable","lightweight portable folding chair"),
        ("highchair","baby feeding chair","chair","seating|baby","tall baby chair with front tray"),
        ("stool","footstool","furniture","seating","small backless round stool"),
        ("ottoman","pouf|footrest","furniture","seating|living_room","padded square footrest seat"),
        ("chaise longue","chaise|daybed","sofa","seating|living_room","long reclining lounge chair"),
        ("beanbag","bean bag chair","chair","seating|casual","soft fabric bean-filled seat"),
        ("bench","","furniture","seating","long flat wooden or metal bench"),
        ("deck chair","beach chair|sun lounger","chair","seating|outdoor","folding reclining outdoor chair"),
        ("table","","furniture","surfaces","flat-top table with supporting legs"),
        ("dining table","dinner table","table","surfaces|kitchen","large rectangular wooden dining table"),
        ("coffee table","cocktail table","table","surfaces|living_room","low rectangular living room table"),
        ("desk","writing desk|work desk","table","surfaces|office","flat work surface with legs"),
        ("side table","end table|accent table","table","surfaces|living_room","small table placed beside sofa"),
        ("console table","hallway table","table","surfaces|entryway","narrow wall-side hallway table"),
        ("bed","double bed|queen bed|king bed","furniture","sleeping|bedroom","full-size bed frame with headboard"),
        ("bunk bed","stacked bed","bed","sleeping|bedroom|children","two-tier stacked metal bed frame"),
        ("crib","baby cot|infant bed","bed","sleeping|baby","enclosed slatted baby sleeping crib"),
        ("futon","sofa bed","furniture","sleeping|seating","foldable sofa that converts into bed"),
        ("mattress","","bed","sleeping|bedroom","padded rectangular sleeping mattress"),
        ("bookcase","bookshelf|shelving unit","furniture","storage|living_room","tall open shelving unit for books"),
        ("wardrobe","armoire|clothes cabinet","furniture","storage|bedroom","tall cabinet for hanging clothes"),
        ("dresser","chest of drawers|bureau","furniture","storage|bedroom","wide chest with multiple drawers"),
        ("nightstand","bedside table|night table","furniture","storage|bedroom","small bedside table with drawer"),
        ("cabinet","storage cabinet","furniture","storage","enclosed cabinet with hinged doors"),
        ("tv stand","media console|entertainment unit","furniture","storage|living_room","low cabinet supporting television"),
        ("shelving unit","open shelf|wall shelf","furniture","storage","open multi-level shelving unit"),
        ("cupboard","kitchen cupboard","cabinet","storage|kitchen","wall-mounted kitchen storage cupboard"),
        ("coat rack","hat rack|hallway stand","furniture","storage|entryway","freestanding rack for coats and hats"),
        ("shoe rack","shoe organizer","furniture","storage|entryway","low rack for organizing footwear"),
        ("hammock","","furniture","sleeping|outdoor","hanging woven rope or fabric hammock"),
        ("piano stool","music stool","stool","seating|music","small height-adjustable piano stool"),
    ],
    "electronics": [
        ("smartphone","cell phone|mobile phone|cellphone","electronics","portable|personal","slim touchscreen smartphone device"),
        ("laptop","notebook computer|laptop computer","electronics","portable|personal","slim portable computer with keyboard"),
        ("tablet","tablet computer|ipad","electronics","portable|personal","flat touchscreen tablet device"),
        ("smartwatch","smart watch","electronics","wearable|personal","digital smartwatch with touchscreen display"),
        ("e-reader","ebook reader|kindle","electronics","portable|personal","slim device for digital book reading"),
        ("television","tv|tv set","electronics","display|entertainment","large flat-panel television screen"),
        ("computer monitor","desktop monitor|pc screen","electronics","display|office","flat-panel computer display monitor"),
        ("projector","video projector","electronics","display|office","device projecting images onto screen"),
        ("speaker","audio speaker","electronics","audio","standalone audio speaker unit"),
        ("bluetooth speaker","wireless speaker|portable speaker","speaker","audio|portable","portable cylindrical wireless speaker"),
        ("headphones","over-ear headphones","electronics","audio|wearable","cushioned over-ear audio headphones"),
        ("earphones","earbuds|in-ear headphones","electronics","audio|wearable|portable","small in-ear audio earbuds"),
        ("microphone","mic|studio mic","electronics","audio|recording","standalone directional audio microphone"),
        ("subwoofer","bass speaker","electronics","audio","large enclosure low-frequency bass speaker"),
        ("keyboard","computer keyboard","electronics","input|office","rectangular computer input keyboard"),
        ("computer mouse","mouse|wireless mouse","electronics","input|office","handheld computer pointing device"),
        ("mousepad","mouse mat","electronics","input|office","flat desk mat for computer mouse"),
        ("webcam","web camera|streaming camera","electronics","camera|input","clip-on camera for video calls"),
        ("game controller","gamepad|gaming controller","electronics","input|gaming","wireless gaming thumbstick controller"),
        ("joystick","flight stick","electronics","input|gaming","tall handheld gaming joystick"),
        ("digital camera","dslr camera|mirrorless camera","electronics","camera|portable","digital single-lens reflex camera"),
        ("video camera","camcorder","electronics","camera|recording","handheld video recording camcorder"),
        ("action camera","gopro","electronics","camera|portable|outdoor","compact mountable action camera"),
        ("tripod","camera tripod","electronics","camera|accessories","three-legged adjustable camera support stand"),
        ("router","wifi router|wireless router","electronics","networking","rectangular home wireless router"),
        ("flash drive","usb drive|thumb drive|usb stick","electronics","storage|portable","small rectangular usb flash drive"),
        ("external hard drive","portable hard drive","electronics","storage|portable","compact portable hard disk drive"),
        ("power strip","extension cord|power bar","electronics","power","multi-socket plastic electrical power strip"),
        ("phone charger","usb charger|charging cable","electronics","power|portable","cable and wall adapter for charging"),
        ("battery pack","power bank|portable charger","electronics","power|portable","rectangular portable battery charger"),
        ("game console","gaming console|video game console","electronics","gaming|entertainment","home tabletop video game console"),
        ("remote control","tv remote|remote","electronics","input|entertainment","handheld infrared remote control"),
        ("alarm clock","digital alarm clock|bedside clock","electronics","timekeeping","small digital bedside alarm clock"),
        ("radio","fm radio|portable radio","electronics","audio|entertainment","rectangular portable fm radio receiver"),
        ("record player","turntable|phonograph","electronics","audio|entertainment","vinyl record turntable player"),
        ("smart speaker","voice assistant speaker","electronics","audio|smart_home","cylindrical voice-controlled smart speaker"),
        ("headset","gaming headset|computer headset","electronics","audio|gaming|wearable","headphones with attached microphone"),
        ("calculator","pocket calculator","electronics","office|portable","slim handheld digital calculator"),
        ("cd player","disc player","electronics","audio|entertainment","standalone compact disc audio player"),
        ("laptop stand","notebook stand","electronics","accessories|office","adjustable folding metal laptop stand"),
    ],
    "kitchenware": [
        ("ceramic mug","coffee mug|tea mug","kitchenware","drinkware","ceramic drinking mug with handle"),
        ("drinking glass","water glass|glass","kitchenware","drinkware","clear cylindrical drinking glass"),
        ("wine glass","red wine glass|white wine glass","kitchenware","drinkware","stemmed bowl-shaped wine glass"),
        ("champagne flute","flute glass","kitchenware","drinkware","tall narrow champagne flute glass"),
        ("shot glass","","kitchenware","drinkware","small thick-walled shot glass"),
        ("teacup","tea cup|china cup","kitchenware","drinkware","small delicate teacup with handle"),
        ("thermos","vacuum flask|insulated flask","kitchenware","drinkware|portable","tall insulated stainless thermos flask"),
        ("travel mug","travel cup|to-go cup","kitchenware","drinkware|portable","lidded insulated travel coffee mug"),
        ("dinner plate","ceramic plate|plate","kitchenware","dishware","round flat white ceramic dinner plate"),
        ("soup bowl","bowl|ceramic bowl","kitchenware","dishware","deep round ceramic soup bowl"),
        ("salad bowl","large mixing bowl","kitchenware","dishware","wide shallow salad serving bowl"),
        ("serving platter","platter|serving dish","kitchenware","dishware","large oval ceramic serving platter"),
        ("saucer","teacup saucer","kitchenware","dishware","small flat dish placed under teacup"),
        ("cooking pot","stockpot|large pot","kitchenware","cookware","tall stainless cooking pot with lid"),
        ("saucepan","small pot","kitchenware","cookware","small metal pot with single long handle"),
        ("frying pan","skillet|pan","kitchenware","cookware","flat circular metal frying pan"),
        ("wok","stir-fry wok","kitchenware","cookware","round-bottomed deep steel wok pan"),
        ("baking tray","sheet pan|baking sheet","kitchenware","cookware","flat rectangular metal baking tray"),
        ("casserole dish","baking dish|oven dish","kitchenware","cookware","deep oval ceramic oven casserole dish"),
        ("dutch oven","cast iron pot","kitchenware","cookware","heavy cast iron enameled cooking pot"),
        ("kitchen knife","chef knife|cook's knife","kitchenware","utensils","wide-blade steel chef kitchen knife"),
        ("fork","dining fork|table fork","kitchenware","utensils","metal four-tined dining fork"),
        ("spoon","tablespoon|soup spoon","kitchenware","utensils","round-bowled metal soup spoon"),
        ("chopsticks","","kitchenware","utensils","pair of wooden or bamboo chopsticks"),
        ("spatula","cooking spatula|turner","kitchenware","utensils","flat flexible food-flipping spatula"),
        ("wooden spoon","","kitchenware","utensils","long-handled wooden stirring spoon"),
        ("ladle","soup ladle|serving ladle","kitchenware","utensils","deep long-handled serving ladle"),
        ("tongs","kitchen tongs","kitchenware","utensils","spring-grip stainless steel kitchen tongs"),
        ("whisk","balloon whisk|egg whisk","kitchenware","utensils","wire loop balloon whisk"),
        ("rolling pin","dough roller","kitchenware","utensils","smooth cylindrical wooden rolling pin"),
        ("grater","box grater|cheese grater","kitchenware","utensils","metal box grater with multiple holes"),
        ("peeler","vegetable peeler","kitchenware","utensils","Y-shaped or straight vegetable peeler"),
        ("can opener","tin opener","kitchenware","utensils","manual or electric tin can opener"),
        ("cutting board","chopping board","kitchenware","prep_tools","wooden or plastic food cutting board"),
        ("colander","pasta strainer","kitchenware","prep_tools","perforated bowl-shaped metal colander"),
        ("measuring cup","","kitchenware","prep_tools","clear graduated liquid measuring cup"),
        ("toaster","bread toaster|pop-up toaster","kitchenware","appliances","stainless countertop bread toaster"),
        ("microwave oven","microwave","kitchenware","appliances|electronics","countertop rectangular microwave oven"),
        ("electric kettle","kettle|jug kettle","kitchenware","appliances|electronics","electric water-boiling plastic kettle"),
        ("coffee maker","drip coffee maker|coffee machine","kitchenware","appliances","automatic drip coffee machine"),
        ("blender","smoothie blender|jug blender","kitchenware","appliances|electronics","tall jug blender with blade"),
        ("food processor","","kitchenware","appliances|electronics","wide-bowl electric food processor"),
        ("stand mixer","kitchen mixer","kitchenware","appliances|electronics","countertop tilt-head stand mixer"),
        ("rice cooker","","kitchenware","appliances|electronics","domed electric rice cooking pot"),
        ("dishwasher","dishwashing machine","kitchenware","appliances|electronics","under-counter household dishwasher"),
        ("refrigerator","fridge|icebox","kitchenware","appliances|electronics","tall white household refrigerator"),
        ("kitchen stove","cooker|gas stove|oven range","kitchenware","appliances|electronics","freestanding kitchen stove with burners"),
        ("oven","baking oven|wall oven","kitchenware","appliances|electronics","built-in or countertop cooking oven"),
        ("air fryer","","kitchenware","appliances|electronics","compact countertop hot-air fryer"),
    ],
    "clothing": [
        ("t-shirt","tshirt|tee shirt","clothing","tops|casual","short-sleeve plain cotton t-shirt"),
        ("dress shirt","button-up shirt|formal shirt","clothing","tops|formal","collared button-front formal shirt"),
        ("blouse","women's blouse","clothing","tops|women","lightweight women's fabric blouse"),
        ("sweater","pullover|jumper","clothing","tops|winter","knit crew-neck pullover sweater"),
        ("hoodie","hooded sweatshirt","clothing","tops|casual","fleece hooded pullover sweatshirt"),
        ("jacket","casual jacket","clothing","tops|outerwear","casual lightweight zip-up jacket"),
        ("blazer","sport coat|suit jacket","clothing","tops|formal","tailored single-button front blazer"),
        ("coat","winter coat|overcoat","clothing","tops|outerwear|winter","long heavy belted overcoat"),
        ("trench coat","mac coat","clothing","tops|outerwear","double-breasted belted trench coat"),
        ("raincoat","waterproof jacket|anorak","clothing","tops|outerwear","hooded waterproof rain jacket"),
        ("parka","padded jacket|down jacket","clothing","tops|outerwear|winter","insulated hooded winter parka"),
        ("vest","waistcoat|gilet","clothing","tops|formal","sleeveless formal waistcoat vest"),
        ("tank top","sleeveless top|singlet","clothing","tops|casual","sleeveless fitted ribbed tank top"),
        ("polo shirt","polo|golf shirt","clothing","tops|smart_casual","short-sleeve collared polo shirt"),
        ("cardigan","knit cardigan|open cardigan","clothing","tops|casual","open-front knit button cardigan"),
        ("sweatshirt","crewneck sweatshirt","clothing","tops|casual","plain crew-neck cotton sweatshirt"),
        ("turtleneck","polo neck","clothing","tops|winter","high-neck fitted turtleneck top"),
        ("jeans","denim jeans|blue jeans","clothing","bottoms|casual","classic five-pocket blue denim jeans"),
        ("trousers","pants|slacks","clothing","bottoms|formal","straight-leg formal fabric trousers"),
        ("shorts","short pants","clothing","bottoms|casual","above-knee casual shorts"),
        ("skirt","midi skirt|pencil skirt","clothing","bottoms|women","women's fabric knee-length skirt"),
        ("leggings","","clothing","bottoms|women|activewear","tight stretch fabric leggings"),
        ("sweatpants","joggers|track pants","clothing","bottoms|casual","loose fleece drawstring sweatpants"),
        ("dress","sundress|summer dress","clothing","full_outfit|women","women's one-piece fabric dress"),
        ("jumpsuit","romper|one-piece suit","clothing","full_outfit","one-piece top-and-trousers jumpsuit"),
        ("overalls","dungarees|bib overalls","clothing","full_outfit|workwear","bib-front denim overalls"),
        ("suit","business suit","clothing","full_outfit|formal","matching jacket-and-trousers business suit"),
        ("tuxedo","dinner suit|black tie","clothing","full_outfit|formal","formal black satin-lapel tuxedo"),
        ("pajamas","pyjamas|sleepwear","clothing","full_outfit|sleepwear","matching loose cotton pajama set"),
        ("swimsuit","bathing suit|swimming costume","clothing","full_outfit|swimwear","one or two-piece swimsuit"),
        ("bathrobe","robe|dressing gown","clothing","full_outfit|sleepwear","thick terry-cloth bathrobe"),
        ("sneaker","tennis shoe|trainer|running shoe","clothing","footwear|casual","rubber-soled lace-up sneaker"),
        ("boot","ankle boot|leather boot","clothing","footwear","lace-up leather ankle or knee boot"),
        ("sandal","summer sandal|flat sandal","clothing","footwear|summer","open-toe strappy flat sandal"),
        ("slipper","house slipper","clothing","footwear|indoor","soft indoor terry-cloth house slipper"),
        ("flip-flop","thong sandal|jandal","clothing","footwear|summer","flat rubber Y-strap flip-flop"),
        ("hat","sun hat|wide-brim hat","clothing","headwear","wide-brimmed woven sun hat"),
        ("baseball cap","cap|snapback","clothing","headwear|casual","curved-brim adjustable baseball cap"),
        ("beanie","knit hat|winter hat","clothing","headwear|winter","close-fitting ribbed knit wool beanie"),
        ("scarf","neck scarf|winter scarf","clothing","accessories|winter","long soft woven neck scarf"),
        ("glove","winter glove|leather glove","clothing","accessories|winter","fitted warm winter glove"),
        ("belt","leather belt|fabric belt","clothing","accessories","flat leather or fabric waist belt"),
        ("necktie","tie|neck tie","clothing","accessories|formal","long silk or woven neck tie"),
        ("bow tie","bowtie","clothing","accessories|formal","small clip-on or tied bow tie"),
        ("sunglasses","shades|sunnies","clothing","accessories|eyewear","tinted UV-protective sunglasses"),
        ("eyeglasses","glasses|spectacles","clothing","accessories|eyewear","corrective lens eyeglasses frame"),
        ("watch","wristwatch","clothing","accessories|electronics","wrist-worn analog or digital watch"),
        ("bracelet","bangle|wrist bracelet","clothing","accessories|jewelry","decorative metal or bead bracelet"),
        ("necklace","neck chain","clothing","accessories|jewelry","beaded or chain necklace"),
        ("earring","stud earring|hoop earring","clothing","accessories|jewelry","small metal or gemstone earring"),
        ("ring","finger ring","clothing","accessories|jewelry","small metal finger ring"),
        ("backpack","rucksack|knapsack","clothing","accessories|bags","zippered multi-pocket fabric backpack"),
        ("handbag","purse|pocketbook","clothing","accessories|bags","handled women's fabric or leather bag"),
        ("tote bag","shopping tote","clothing","accessories|bags","large open-top canvas tote bag"),
        ("shoulder bag","cross-body bag|satchel","clothing","accessories|bags","strap-worn shoulder or cross-body bag"),
        ("wallet","billfold","clothing","accessories|bags","slim bi-fold leather wallet"),
        ("suitcase","luggage|travel bag","clothing","accessories|bags","hard or soft-shell rolling suitcase"),
        ("sock","ankle sock|knee sock","clothing","footwear","short or long knit cotton sock"),
        ("underwear","underpants|briefs","clothing","base_layer","elasticated cotton underwear briefs"),
        ("bra","brassiere","clothing","base_layer|women","women's supportive underwire bra"),
        ("tights","pantyhose|stockings","clothing","base_layer|women","sheer or opaque nylon tights"),
    ],
    "office": [
        ("pen","ballpoint pen|ink pen","office","writing","ballpoint or gel ink writing pen"),
        ("pencil","graphite pencil","office","writing","wooden hexagonal graphite pencil"),
        ("marker","felt-tip marker|permanent marker","office","writing","thick-tip permanent felt marker"),
        ("highlighter","highlight pen","office","writing","wide fluorescent ink highlighter pen"),
        ("eraser","rubber eraser","office","writing","rectangular white rubber block eraser"),
        ("pencil sharpener","sharpener","office","writing","cylindrical handheld pencil sharpener"),
        ("notebook","spiral notebook|exercise book","office","paper","spiral-bound ruled writing notebook"),
        ("notepad","writing pad|memo pad","office","paper","small tear-off lined writing pad"),
        ("sticky note","post-it note","office","paper","small self-adhesive square sticky note"),
        ("folder","document folder|file folder","office","paper","cardboard A4 document folder"),
        ("binder","ring binder|lever arch file","office","paper","wide D-ring document binder"),
        ("clipboard","","office","paper","rigid clip-back writing support board"),
        ("scissors","craft scissors|office scissors","office","desk_tools","pair of steel blade scissors"),
        ("ruler","measuring ruler|straight edge","office","desk_tools","transparent or wooden flat ruler"),
        ("stapler","desk stapler","office","desk_tools","spring-loaded desk paper stapler"),
        ("tape dispenser","scotch tape dispenser","office","desk_tools","weighted desk sticky tape dispenser"),
        ("paper clip","binder clip|metal clip","office","desk_tools","small springy metal paper clip"),
        ("binder clip","bulldog clip|fold-back clip","office","desk_tools","large metal spring binder clip"),
        ("thumbtack","drawing pin|pushpin","office","desk_tools","sharp-pointed colored thumbtack pin"),
        ("hole punch","paper punch","office","desk_tools","two-hole spring paper punch"),
        ("desk organizer","pen holder|desk caddy","office","desk_tools","multi-compartment desk organizer"),
        ("calendar","desk calendar|wall calendar","office","desk_tools","tear-off monthly paper calendar"),
        ("letter tray","in-tray|paper tray","office","desk_tools","flat stackable desk document tray"),
        ("envelope","mailing envelope","office","paper","white paper mailing envelope"),
        ("index card","flash card|cue card","office","paper","small ruled rectangular index card"),
        ("rubber band","elastic band","office","desk_tools","small stretchy rubber office band"),
        ("pencil case","pencil pouch","office","storage","zippered fabric pencil storage pouch"),
        ("whiteboard","dry-erase board","office","display","white magnetic dry-erase writing board"),
        ("bulletin board","notice board|cork board","office","display","cork-surface wall notice board"),
        ("filing cabinet","file cabinet","office","storage","tall metal multi-drawer filing cabinet"),
        ("printer","inkjet printer|laser printer","office","technology|electronics","desktop document inkjet printer"),
        ("paper shredder","document shredder","office","technology|electronics","desktop paper shredding machine"),
        ("label maker","labeler|label printer","office","technology|electronics","handheld label printing device"),
        ("stamp","rubber stamp","office","desk_tools","wooden-handled rubber ink stamp"),
        ("staple remover","staple puller","office","desk_tools","claw-grip metal staple remover"),
    ],
}
