"""concept_registry_b.py — Phase 1 concepts: bathroom, tools, household, food, outdoor."""

# fmt: (canonical_label, aliases, parent, tags, visual_description)

CONCEPTS_B = {
    "bathroom": [
        ("toothbrush","manual toothbrush","bathroom","dental","nylon-bristle manual toothbrush"),
        ("toothpaste","dental paste","bathroom","dental","white tube of fluoride toothpaste"),
        ("electric toothbrush","powered toothbrush","bathroom","dental|electronics","rechargeable oscillating toothbrush"),
        ("dental floss","floss thread","bathroom","dental","small round container of dental floss"),
        ("mouthwash","mouth rinse|gargle","bathroom","dental","tall bottle of antiseptic mouthwash"),
        ("shampoo","hair shampoo","bathroom","hair_care","plastic bottle of hair washing shampoo"),
        ("conditioner","hair conditioner","bathroom","hair_care","pump bottle of hair conditioner"),
        ("soap bar","bath soap|hand soap bar","bathroom","skincare","rectangular white bath soap bar"),
        ("liquid soap dispenser","soap pump|hand soap pump","bathroom","skincare","pump-top bottle of liquid hand soap"),
        ("face wash","facial cleanser|face scrub","bathroom","skincare","tube or bottle of facial cleanser"),
        ("body lotion","skin lotion|moisturizer","bathroom","skincare","pump bottle of moisturizing body lotion"),
        ("razor","shaving razor|disposable razor","bathroom","grooming","handled multi-blade shaving razor"),
        ("electric shaver","electric razor","bathroom","grooming|electronics","cordless rotary electric shaver"),
        ("shaving cream","shaving foam|shave gel","bathroom","grooming","aerosol can of shaving foam"),
        ("hair dryer","blow dryer|hairdryer","bathroom","hair_care|electronics","handheld pistol-grip electric hair dryer"),
        ("hairbrush","hair brush","bathroom","hair_care","oval-cushion paddle hairbrush"),
        ("comb","fine-tooth comb","bathroom","hair_care","flat toothed plastic hair comb"),
        ("hair curler","curling iron|curling wand","bathroom","hair_care|electronics","barrel electric hair curling iron"),
        ("nail clipper","nail cutter","bathroom","grooming","spring-hinged metal nail clipper"),
        ("tweezers","eyebrow tweezers","bathroom","grooming","pointed stainless steel tweezers"),
        ("toilet","commode|lavatory","bathroom","fixtures","white porcelain pedestal toilet bowl"),
        ("shower head","rain shower head","bathroom","fixtures","ceiling or wall-mount shower head"),
        ("bathtub","bath tub|soaking tub","bathroom","fixtures","large white porcelain bathtub"),
        ("bathroom sink","washbasin|hand basin","bathroom","fixtures","white ceramic wall-mounted washbasin"),
        ("faucet","tap|water tap","bathroom","fixtures","chrome double-handle basin faucet"),
        ("mirror","bathroom mirror|wall mirror","bathroom","fixtures","rectangular wall-mounted bathroom mirror"),
        ("towel","bath towel|hand towel","bathroom","linens","folded thick cotton bath towel"),
        ("bath mat","bath rug|shower mat","bathroom","linens","non-slip rectangular bath floor mat"),
        ("shower curtain","shower screen","bathroom","fixtures","hanging fabric or plastic shower curtain"),
        ("toilet paper","toilet roll|loo roll","bathroom","hygiene","roll of white toilet tissue paper"),
        ("soap dish","soap holder","bathroom","accessories","rectangular ceramic soap dish"),
        ("medicine cabinet","bathroom cabinet","bathroom","storage","wall-mounted mirrored medicine cabinet"),
        ("toothbrush holder","toothbrush cup","bathroom","accessories","ceramic cup-shaped toothbrush holder"),
        ("tissue box","kleenex box","bathroom","hygiene","rectangular cardboard facial tissue box"),
        ("cotton swab","q-tip|cotton bud","bathroom","hygiene","double-ended white cotton swab stick"),
    ],
    "tools": [
        ("hammer","claw hammer","tools","hand_tools","metal claw hammer with wooden handle"),
        ("screwdriver","flathead screwdriver|phillips screwdriver","tools","hand_tools","handled flat or cross-tip screwdriver"),
        ("wrench","spanner|adjustable wrench","tools","hand_tools","adjustable open-end metal spanner"),
        ("pliers","needle-nose pliers","tools","hand_tools","hinged metal gripping pliers"),
        ("handsaw","wood saw|carpenter saw","tools","hand_tools","toothed metal blade handsaw"),
        ("utility knife","box cutter|stanley knife","tools","hand_tools","retractable blade utility cutter"),
        ("chisel","wood chisel","tools","hand_tools","beveled-edge steel wood chisel"),
        ("mallet","rubber mallet","tools","hand_tools","large-head rubber striking mallet"),
        ("crowbar","pry bar|wrecking bar","tools","hand_tools","curved steel prying crowbar"),
        ("Allen wrench","hex key|allen key","tools","hand_tools","L-shaped hexagonal allen key set"),
        ("measuring tape","tape measure","tools","measuring","retractable spring-loaded measuring tape"),
        ("level tool","spirit level|bubble level","tools","measuring","yellow horizontal spirit level bar"),
        ("power drill","electric drill|cordless drill","tools","power_tools|electronics","cordless trigger-grip power drill"),
        ("jigsaw","electric jigsaw","tools","power_tools|electronics","electric reciprocating blade jigsaw"),
        ("circular saw","disc saw","tools","power_tools|electronics","handheld round-blade circular saw"),
        ("sander","orbital sander","tools","power_tools|electronics","palm-grip orbital surface sander"),
        ("bolt","hex bolt","tools","fasteners","threaded metal hexagonal bolt"),
        ("nut","hex nut|wing nut","tools","fasteners","threaded metal hex fastening nut"),
        ("nail","wire nail|finishing nail","tools","fasteners","sharp-pointed metal wire nail"),
        ("screw","wood screw|machine screw","tools","fasteners","threaded metal Phillips-head screw"),
        ("clamp","g-clamp|bar clamp","tools","fasteners","G-shaped metal screw-grip clamp"),
        ("padlock","combination lock|padlock lock","tools","fasteners|security","shackle padlock with key or code"),
        ("garden hose","water hose|hosepipe","tools","garden","green coiled rubber garden hose"),
        ("rake","leaf rake|garden rake","tools","garden","long-handled fan-head garden rake"),
        ("shovel","spade|garden spade","tools","garden","long-handled flat-blade digging shovel"),
        ("watering can","garden watering can","tools","garden","handled pouring-spout watering can"),
        ("lawn mower","grass mower|push mower","tools","garden|electronics","red or green walk-behind lawn mower"),
        ("wheelbarrow","garden barrow","tools","garden","single-wheel metal garden wheelbarrow"),
        ("pruning shears","secateurs|garden clippers","tools","garden","spring-handled pruning secateurs"),
        ("broom","floor broom|sweep brush","tools","cleaning","long-handled stiff-bristle floor broom"),
        ("dustpan","dustpan and brush","tools","cleaning","flat scoop-shaped metal or plastic dustpan"),
        ("mop","floor mop|string mop","tools","cleaning","long-handled wet string floor mop"),
        ("vacuum cleaner","hoover|vacuum","tools","cleaning|electronics","wheeled or upright electric vacuum cleaner"),
        ("clothes iron","iron|steam iron","tools","cleaning|electronics","triangular soleplate electric steam iron"),
        ("ironing board","iron board","tools","cleaning","padded folding fabric ironing board"),
        ("scrubbing brush","scrub brush|cleaning brush","tools","cleaning","stiff-bristle short-handled scrub brush"),
        ("sponge","cleaning sponge|kitchen sponge","tools","cleaning","rectangular two-sided cleaning sponge"),
        ("toolbox","tool box|tool case","tools","storage","metal or plastic hinged toolbox"),
        ("extension cord","power extension|extension lead","tools","power|electronics","multi-socket plastic extension cord"),
        ("axe","hand axe|hatchet","tools","hand_tools","short-handle steel splitting axe"),
        ("wire cutters","cable cutters|snips","tools","hand_tools","angled blade wire cutting snips"),
        ("paint roller","roller brush","tools","painting","foam roller on telescoping paint handle"),
        ("paintbrush","wall brush|paint brush","tools","painting","wide flat bristle paint brush"),
        ("sandpaper","abrasive paper|grit paper","tools","painting","sheet of coarse or fine sandpaper"),
        ("ladder","step ladder|extension ladder","tools","general","tall aluminum folding step ladder"),
        ("trowel","garden trowel|masonry trowel","tools","garden","small pointed metal digging trowel"),
    ],
    "household": [
        ("floor lamp","standing lamp|torchiere","household","lighting","tall freestanding floor lamp"),
        ("table lamp","bedside lamp","household","lighting","small base-and-shade table lamp"),
        ("desk lamp","reading lamp|adjustable lamp","household","lighting|electronics","adjustable arm LED desk lamp"),
        ("wall lamp","wall sconce|sconce light","household","lighting","wall-mounted decorative light sconce"),
        ("chandelier","ceiling chandelier","household","lighting","hanging multi-arm ceiling chandelier"),
        ("pendant light","hanging light|ceiling pendant light","household","lighting","hanging pendant ceiling light"),
        ("lamp shade","light shade","household","lighting","fabric or glass lampshade cover"),
        ("lightbulb","light bulb|bulb","household","lighting|electronics","glass screw-base light bulb"),
        ("candle","wax candle|pillar candle","household","lighting|decor","cylindrical wax pillar candle"),
        ("candleholder","candle holder|candlestick","household","lighting|decor","metal or ceramic candle holder"),
        ("flashlight","torch|hand torch","household","lighting|portable","cylindrical handheld battery flashlight"),
        ("lantern","outdoor lantern|garden lantern","household","lighting","hanging glass-panel metal lantern"),
        ("ceiling fan","overhead fan","household","climate","white ceiling-mounted rotating fan"),
        ("standing fan","pedestal fan|tower fan","household","climate","tall freestanding electric pedestal fan"),
        ("air conditioner","ac unit|split ac","household","climate|electronics","wall-mount indoor air conditioning unit"),
        ("space heater","electric heater|portable heater","household","climate|electronics","compact electric portable space heater"),
        ("humidifier","room humidifier","household","climate|electronics","cylindrical countertop ultrasonic humidifier"),
        ("wall clock","wall hanging clock","household","timekeeping","round analog face wall clock"),
        ("bedside clock","bedside alarm clock|sleep clock","household","timekeeping","small analog or digital bedside clock"),
        ("hourglass","sand timer|egg timer","household","timekeeping","glass hourglass with wooden frame"),
        ("picture frame","photo frame","household","decor","rectangular glass-front picture frame"),
        ("menu board","cafe menu board|wall menu","household","decor|display","wall mounted cafe menu board"),
        ("vase","flower vase|ceramic vase","household","decor","tall ceramic or glass flower vase"),
        ("flower pot","flowerpot|planter pot","household","decor","terracotta or plastic plant pot"),
        ("painting","framed painting|wall art","household","decor","canvas framed wall painting"),
        ("wind chime","garden chime","household","decor","hanging metal or bamboo wind chime"),
        ("pillow","throw pillow|bed pillow","household","linens","soft square or rectangular pillow"),
        ("blanket","throw blanket|fleece blanket","household","linens","soft woven or fleece blanket"),
        ("cushion","sofa cushion|seat cushion","household","linens","square fabric-covered sofa cushion"),
        ("bed sheet","fitted sheet|flat sheet","household","linens","flat or fitted cotton bed sheet"),
        ("quilt","comforter|duvet","household","linens","thick padded fabric quilt"),
        ("rug","floor rug|area rug","household","linens","rectangular patterned floor area rug"),
        ("curtain","window curtain|drape","household","linens","long hanging window curtain panel"),
        ("window blind","venetian blind|roller blind","household","decor","slatted or rolled window blind"),
        ("door mat","doormat|welcome mat","household","home","flat rubber or coir door mat"),
        ("storage box","storage bin|plastic bin","household","storage","rectangular lidded storage box"),
        ("laundry basket","clothes hamper|laundry hamper","household","storage","woven or plastic laundry basket"),
        ("clothes hanger","coat hanger|wire hanger","household","storage|clothing","curved plastic or wooden clothes hanger"),
        ("umbrella","rain umbrella","household","accessories","folding or full-size rain umbrella"),
        ("keys","key ring|house keys|keychain","household","accessories|personal","small metal keys on key ring"),
        ("indoor trash can","waste bin|rubbish bin|indoor bin","household","cleaning","round plastic indoor trash bin"),
        ("fire extinguisher","extinguisher","household","safety","red cylinder fire extinguisher"),
        ("smoke alarm","fire alarm|smoke detector","household","safety","round white ceiling smoke detector"),
        ("welcome mat","doormat|entrance mat","household","home","flat coir or rubber entrance door mat"),
        ("soap dispenser","lotion dispenser|wall dispenser","household","accessories","wall-mounted or countertop soap dispenser"),
        ("decorative mirror","full-length mirror|floor mirror|wall mirror","household","decor","large framed full-length decorative mirror"),
        ("clock","mantle clock|desk clock","household","timekeeping","small decorative mantle or shelf clock"),
        ("throw pillow","accent pillow|decorative pillow","household","decor","small decorative square accent pillow"),
        ("table runner","dining runner","household","linens","long narrow decorative table runner"),
        ("plant pot","indoor planter|potted plant pot","household","decor","ceramic or terracotta indoor plant pot"),
        ("bookend","book stopper","household","decor","decorative metal or wood bookend pair"),
        ("wicker basket","storage basket|decorative basket","household","storage","woven wicker storage basket"),
        ("ironing basket","laundry sorter","household","storage","tall fabric laundry sorting basket"),
    ],
    "food": [
        ("apple","red apple|green apple","food","fruit","round red or green apple fruit"),
        ("banana","","food","fruit","curved yellow banana fruit"),
        ("orange","orange fruit","food","fruit","round orange citrus fruit"),
        ("grape","grape cluster|green grape|red grape","food","fruit","small cluster of round grapes"),
        ("strawberry","","food","fruit","heart-shaped red strawberry fruit"),
        ("blueberry","blueberries","food","fruit","small round dark blue blueberry"),
        ("watermelon","","food","fruit","large oval green-striped watermelon"),
        ("pineapple","","food","fruit","tall spiky-crowned yellow pineapple"),
        ("mango","","food","fruit","oval yellow-orange mango fruit"),
        ("lemon","yellow lemon","food","fruit","oval bright yellow lemon fruit"),
        ("pear","green pear|yellow pear","food","fruit","bell-shaped green or yellow pear"),
        ("peach","","food","fruit","round fuzzy yellow-pink peach fruit"),
        ("cherry","red cherry","food","fruit","small round dark red cherry fruit"),
        ("kiwi","kiwi fruit|kiwifruit","food","fruit","oval brown-skin kiwi fruit"),
        ("avocado","","food","fruit","dark pear-shaped avocado fruit"),
        ("lime","green lime","food","fruit","small round bright green lime fruit"),
        ("melon","honeydew melon|cantaloupe","food","fruit","round pale green or orange melon"),
        ("raspberry","","food","fruit","small bumpy red raspberry fruit"),
        ("fig","dried fig","food","fruit","small pear-shaped purple fig fruit"),
        ("apricot","","food","fruit","small round orange apricot fruit"),
        ("tomato","red tomato","food","vegetable","round red garden tomato"),
        ("carrot","","food","vegetable","long tapered orange carrot"),
        ("broccoli","","food","vegetable","green tree-shaped broccoli floret"),
        ("potato","white potato|russet potato","food","vegetable","oval rough-skinned brown potato"),
        ("onion","white onion|brown onion","food","vegetable","round paper-skinned onion"),
        ("garlic","garlic bulb|garlic clove","food","vegetable","white papery garlic bulb"),
        ("bell pepper","capsicum|sweet pepper","food","vegetable","blocky red green or yellow pepper"),
        ("lettuce","iceberg lettuce|romaine lettuce","food","vegetable","leafy green head of lettuce"),
        ("cucumber","","food","vegetable","long dark green cylindrical cucumber"),
        ("eggplant","aubergine","food","vegetable","long shiny purple eggplant"),
        ("corn","sweet corn|corn cob","food","vegetable","yellow-kernel corn cob"),
        ("mushroom","button mushroom","food","vegetable","round brown mushroom with stem"),
        ("zucchini","courgette","food","vegetable","long smooth green zucchini"),
        ("cauliflower","","food","vegetable","round white cauliflower head"),
        ("asparagus","asparagus spear","food","vegetable","bundle of green asparagus spears"),
        ("celery","celery stalk","food","vegetable","pale green ribbed celery stalk"),
        ("bread","white bread|sandwich bread","food","grains","loaf of sliced white sandwich bread"),
        ("baguette","french baguette","food","grains","long thin golden French baguette"),
        ("croissant","butter croissant","food","grains","crescent-shaped flaky butter croissant"),
        ("bagel","plain bagel","food","grains","round ring-shaped boiled bread bagel"),
        ("rice","cooked rice|white rice","food","grains","bowl of steamed white cooked rice"),
        ("toast","toasted bread","food","grains","golden toasted bread slice"),
        ("pancake","","food","grains","round flat golden cooked pancake"),
        ("waffle","belgian waffle","food","grains","grid-pattern square waffle"),
        ("pizza","pizza slice|whole pizza","food","prepared","round flat cheese-topped baked pizza"),
        ("hamburger","burger|cheeseburger","food","prepared","stacked beef and bun hamburger"),
        ("sandwich","sub sandwich|deli sandwich","food","prepared","filled two-slice bread sandwich"),
        ("hot dog","frankfurter|sausage in bun","food","prepared","sausage inside split hot-dog bun"),
        ("burrito","wrap burrito","food","prepared","large flour-wrapped stuffed burrito"),
        ("taco","corn taco|taco shell","food","prepared","folded corn shell filled taco"),
        ("sushi","sushi roll|nigiri sushi","food","prepared","rice and fish sushi roll"),
        ("fried egg","sunny side up egg","food","prepared","fried egg in round pan shape"),
        ("omelet","omelette|egg omelette","food","prepared","folded egg omelette"),
        ("pasta","spaghetti|penne pasta","food","prepared","bowl of cooked pasta"),
        ("butter","butter block|butter pat","food","dairy","yellow rectangular butter block"),
        ("cheese","cheddar cheese|sliced cheese","food","dairy","yellow block or sliced cheese"),
        ("yogurt","greek yogurt|yoghurt","food","dairy","small round pot of yogurt"),
        ("milk","carton of milk|milk bottle","food","dairy","white carton or bottle of milk"),
        ("ice cream","ice cream scoop|cone","food","dairy|dessert","scooped ice cream in cone or cup"),
        ("cookie","chocolate chip cookie","food","snack","round flat chocolate chip cookie"),
        ("chocolate bar","candy bar|chocolate block","food","snack","rectangular wrapped chocolate bar"),
        ("birthday cake","layer cake","food","dessert","tiered frosted birthday celebration cake"),
        ("cupcake","fairy cake","food","dessert","small frosted cupcake in paper case"),
        ("donut","doughnut","food","dessert","ring-shaped glazed fried doughnut"),
        ("muffin","blueberry muffin","food","dessert","domed muffin in paper baking cup"),
        ("coffee","cup of coffee|espresso","food","drink","cup or mug of hot black coffee"),
        ("tea","cup of tea|green tea","food","drink","cup or mug of steaming hot tea"),
        ("orange juice","glass of oj","food","drink","glass of bright orange juice"),
        ("soda","soft drink|cola|canned soda","food","drink","can or glass of fizzy soda drink"),
        ("smoothie","fruit smoothie","food","drink","tall glass of blended fruit smoothie"),
        ("hot chocolate","cocoa drink","food","drink","mug of creamy hot chocolate drink"),
        ("milkshake","milk shake","food","drink","tall glass of thick creamy milkshake"),
    ],
    "outdoor": [
        ("bicycle","bike|push bike","outdoor","vehicle","two-wheeled pedal-driven bicycle"),
        ("motorcycle","motorbike","outdoor","vehicle","two-wheeled gasoline motor motorcycle"),
        ("car","automobile|sedan","outdoor","vehicle","four-door passenger sedan car"),
        ("bus","city bus|double-decker bus","outdoor","vehicle","large multi-passenger city bus"),
        ("truck","delivery truck|lorry","outdoor","vehicle","large cargo delivery truck"),
        ("van","minivan|cargo van","outdoor","vehicle","boxy passenger or cargo van"),
        ("scooter","motor scooter|moped","outdoor","vehicle","small two-wheel electric or gas scooter"),
        ("taxi","cab|yellow cab","outdoor","vehicle","yellow or marked taxi cab"),
        ("school bus","yellow school bus","outdoor","vehicle","bright yellow school children bus"),
        ("skateboard","","outdoor","vehicle|sports","narrow wooden deck four-wheel skateboard"),
        ("traffic light","stoplight|traffic signal","outdoor","street","three-light vertical traffic signal"),
        ("stop sign","","outdoor","street","red octagonal STOP road sign"),
        ("street sign","road sign|direction sign","outdoor","street","metal pole-mounted street name sign"),
        ("mailbox","post box|letter box","outdoor","street","red or metal curbside mailbox"),
        ("fire hydrant","fire plug|hydrant","outdoor","street","red or yellow cast iron fire hydrant"),
        ("parking meter","coin meter","outdoor","street","pole-mounted coin parking meter"),
        ("street lamp","streetlight|lamp post","outdoor","street","tall metal pole-mounted street lamp"),
        ("outdoor bench","park bench|street bench","outdoor","street","wooden slatted outdoor street bench"),
        ("bicycle rack","bike rack|cycle stand","outdoor","street","metal U-shaped bicycle parking rack"),
        ("billboard","advertising billboard","outdoor","street","large roadside advertising billboard"),
        ("litter bin","outdoor bin|public trash can","outdoor","street","metal or plastic outdoor litter bin"),
        ("surfboard","surf board","outdoor","sports","long narrow foam surfboard"),
        ("snowboard","","outdoor","sports","wide short winter snowboard"),
        ("ski","snow ski|downhill ski","outdoor","sports","long narrow downhill snow ski"),
        ("tennis racket","tennis racquet","outdoor","sports","oval-head strung tennis racket"),
        ("basketball","","outdoor","sports","large round orange basketball"),
        ("soccer ball","football ball","outdoor","sports","round black-and-white soccer ball"),
        ("baseball bat","","outdoor","sports","cylindrical tapered wooden baseball bat"),
        ("football","american football","outdoor","sports","oval brown stitched American football"),
        ("frisbee","flying disc","outdoor","sports","flat round plastic throwing disc"),
        ("swing","playground swing","outdoor","play","rubber-seat hanging playground swing"),
        ("playground slide","children's slide","outdoor","play","tall plastic or metal playground slide"),
        ("picnic table","outdoor dining table","outdoor","play","wooden picnic table with attached benches"),
        ("kite","diamond kite","outdoor","play","diamond-shaped fabric or plastic kite"),
        ("volleyball","","outdoor","sports","round white and blue volleyball"),
        ("rugby ball","rugby","outdoor","sports","oval brown leather rugby ball"),
        ("golf club","golf iron|golf driver","outdoor","sports","long-shafted metal head golf club"),
        ("hockey stick","ice hockey stick","outdoor","sports","long curved ice hockey stick"),
        ("tennis ball","","outdoor","sports","small round yellow tennis ball"),
        ("baseball","","outdoor","sports","small white stitched baseball"),
        ("helmet","bike helmet|sports helmet","outdoor","sports|safety","hard-shell protective sports helmet"),
        ("life jacket","life vest|buoyancy aid","outdoor","safety|sports","orange foam-padded life jacket"),
        ("tent","camping tent|dome tent","outdoor","camping","dome-shaped nylon camping tent"),
        ("backpack frame","hiking pack|trekking backpack","outdoor","camping|clothing","large framed hiking backpack"),
        ("fire truck","fire engine","outdoor","vehicle","red emergency fire truck"),
        ("ambulance","","outdoor","vehicle","white medical emergency ambulance van"),
        ("police car","patrol car","outdoor","vehicle","marked black and white police patrol car"),
        ("traffic cone","road cone|safety cone","outdoor","street","bright orange plastic traffic cone"),
        ("guardrail","safety barrier|road barrier","outdoor","street","metal roadside safety guardrail"),
        ("bus stop sign","bus shelter sign","outdoor","street","pole-mounted bus route stop sign"),
        ("crosswalk sign","pedestrian crossing sign","outdoor","street","yellow diamond pedestrian crossing sign"),
        ("vending machine","","outdoor","street","tall glass-front coin-operated vending machine"),
    ],
}
